#!/bin/bash -eu

. ./common.sh
common_init "$@"

pkgver=8.17.0
fetch_web "https://curl.se/download/curl-$pkgver.tar.bz2" \
	230032528ce5f85594d4f3eace63364c4244ccc3c801b7f8db1982722f2761f4
unpack_tar "curl-$pkgver.tar.bz2" --strip-components=1

zlibpath=$(depend_get_path zlib)
options=(
	-DBUILD_STATIC_LIBS=OFF -DCURL_USE_SCHANNEL=ON
	-DCURL_DISABLE_{DOH,GOPHER,IMAP,KERBEROS_AUTH,MQTT,POP3,RTSP,SMTP,SRP,TELNET,TFTP}=ON
	-DCURL_USE_LIBPSL=OFF
	-DCURL_ZLIB=ON -DZLIB_INCLUDE_DIR="$zlibpath/include" -DZLIB_LIBRARY="$zlibpath/lib/libz.dll.a"
	-DCURL_ZSTD=OFF
)
cmake . "${CMAKE_FLAGS[@]}" "${options[@]}"
make

common_flat_tree
make DESTDIR=$INSTALL_DIR install
rm -f $INSTALL_DIR/bin/curl-config
common_tidy

package $pkgver
