#!/bin/bash -eu

. ./common.sh
common_init "$@"

pkgver=8.17.0
fetch_web "https://curl.se/download/curl-$pkgver.tar.bz2" \
	230032528ce5f85594d4f3eace63364c4244ccc3c801b7f8db1982722f2761f4
unpack_tar "curl-$pkgver.tar.bz2" --strip-components=1

zlibpath=$(depend_get_path zlib)
mbedtlspath=$(depend_get_path mbedtls)
echo $mbedtlspath # this prints out the correct path
options=(
	-DBUILD_SHARED_LIBS=OFF
	-DBUILD_STATIC_LIBS=ON -DCURL_USE_SCHANNEL=OFF
	-DBUILD_CURL_EXE=OFF
	-DCURL_DISABLE_{ALTSVC,AWS,BASIC_AUTH,BEARER_AUTH,BINDLOCAL,DICT,DIGEST_AUTH,DOH,FTP,GOPHER,HSTS,IMAP,IPFS,KERBEROS_AUTH,LDAP,LDAPS,MQTT,NEGOTIATE_AUTH,NTLM,PARSEDATE,POP3,RTSP,SMB,SMTP,SOCKETPAIR,SRP,TELNET,TFTP,WEBSOCKETS}=ON
	-DCURL_USE_LIBPSL=OFF
	-DCURL_USE_OPENSSL=OFF
	-DCURL_USE_MBEDTLS=ON
	-DMBEDTLS_INCLUDE_DIR="$mbedtlspath/include"
	-DMBEDTLS_LIBRARY="$mbedtlspath/lib/libmbedtls.a"
	-DMBEDTLS_X509_LIBRARY="$mbedtlspath/lib/libmbedx509.a"
	-DMBEDTLS_CRYPTO_LIBRARY="$mbedtlspath/lib/libmbedcrypto.a"
	-DCURL_ZLIB=ON -DZLIB_INCLUDE_DIR="$zlibpath/include" -DZLIB_LIBRARY="$zlibpath/lib/libz.dll.a"
	-DCURL_ZSTD=OFF
	-DCURL_CA_BUNDLE="data/curl-ca-bundle.crt"
)

cmake . "${CMAKE_FLAGS[@]}" "${options[@]}"
make

common_flat_tree
make DESTDIR=$INSTALL_DIR install
rm -f $INSTALL_DIR/bin/curl-config
common_tidy

package $pkgver
